env:
    global:
        - REPO_DIR=tornado
        - BUILD_COMMIT=v4.3.0
        - BUILD_DEPENDS=
        - TEST_DEPENDS=
        - PLAT=x86_64
        - UNICODE_WIDTH=32

sudo: required
dist: trusty
services:
  - docker
language:
  - python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 2.7
      env:
        - UNICODE_WIDTH=16
    - os: linux
      python: 2.7
      env:
        - PLAT=i686
    - os: linux
      python: 2.7
      env:
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      python: 3.4
    - os: linux
      python: 3.4
      env:
        - PLAT=i686
    - os: linux
      python: 3.5
    - os: linux
      python: 3.5
      env:
        - PLAT=i686
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.4
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - git clone https://github.com/facebook/tornado
    - (cd $REPO_DIR && git checkout $BUILD_COMMIT)
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
