language:
- objective-c
script:
- if [[ $(sudo which -a virtualenv) =~ sr/local/bin/virtualen ]]; then
  sudo pip uninstall -y virtualenv;
  fi
- if [[ $(sudo which -a pip) =~ sr/local/bin/pi ]]; then
  sudo pip uninstall -y pip;
  fi
