env:
    global:
        - REPO_DIR=tornado
        - PLAT=x86_64
        - UNICODE_WIDTH=32

sudo: required
dist: trusty
services:
  - docker
language:
  - python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - source multibuild/travis_steps.sh
    - before_install

install:
    - mkdir tornado
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
