language:
- python

matrix:
  include:
    - os: linux
      python: 2.7
      dist: trusty
      env: PIP_FLAGS="--pre"
    - os: linux
      python: 3.5
      dist: trusty
      env: PIP_FLAGS="--pre"
    - os: linux
      python: 2.7
      env: WITH_PYAMG=1 MINIMUM_REQUIREMENTS=1 WITH_QT=1
    - os: linux
      python: 3.4
      env: OPTIONAL_DEPS=1 WITH_PYSIDE=1
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        git clone https://github.com/MacPython/terryfy.git;
        source terryfy/travis_tools.sh;
        get_python_environment macpython $TRAVIS_PYTHON_VERSION venv;
        source venv/bin/activate;
      fi

script:
- uname -a
- which python
- python --version
- python -c "import distutils.util; print(distutils.util.get_platform())"
- python -c "import sys; print(sys.maxunicode == 65535)"
- which pip
