env:
    global:
        - REPO_DIR=tornado
        - BUILD_COMMIT=v4.3.0
        - BUILD_DEPENDS=
        - TEST_DEPENDS=
        - PLAT=x86_64
        - UNICODE_WIDTH=32

sudo: required
dist: trusty
services:
  - docker
language:
  - python

matrix:
  include:
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - pip install -f https://nipy.bic.berkeley.edu/manylinux numpy==1.8.2

script:
    - python -c 'from numpy.distutils.core import setup'
